name: Pull request checks

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: .go-version

      - name: Lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.4.0
