name: Pull request checks

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6

      - name: Lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.4.0
